image: java:8-jdk

before_script:
- sudo chmod +x ./gradlew

stages:
- build
- deploy

build:
  stage: build
  tags:
  - www
  script:
  - sudo ./gradlew clean assemble

deploy:
  stage: deploy
  tags:
  - www
  script:
  - ls
  only:
  - master