stages:
- build
- test
- deploy

cache:
  paths:
  - .gradle

build:
  stage: build
  tags:
  - www
  artifacts:
    paths:
    - build/libs/*.jar
  script:
  - ./gradlew shadowJar

test:
  stage: test
  tags:
  - www
  script:
  - ./gradlew check

deploy:
  stage: deploy
  tags:
  - www
  script:
  - sudo cp -rf build/libs/animation-server-0.1-all.jar /opt/server.jar
  only:
  - master
  dependencies:
  - build