image: java:8-jdk

before_script:
- sudo chmod +x ./gradlew

stages:
- build
- deploy

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

build:
  stage: build
  tags:
  - www
  script:
  - sudo ./gradlew assemble

deploy:
  stage: deploy
  tags:
  - www
  script:
  - ls
  only:
  - master