before_script:
- chmod +x ./gradlew

stages:
- build
- test
- deploy

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

build:
  stage: build
  tags:
  - www
  script:
  - ./gradlew assemble

test:
  stage: test
  tags:
  - www
  script:
  - ./gradlew check

deploy:
  stage: deploy
  tags:
  - www
  script:
  - ls
  only:
  - master