stages:
- build
- test
- deploy

cache:
  paths:
  - .gradle

build:
  stage: build
  tags:
  - www
  artifacts:
    paths:
    - build/libs/*.jar
  script:
  - ./gradlew assemble

test:
  stage: test
  tags:
  - www
  script:
  - ./gradlew check

deploy:
  stage: deploy
  tags:
  - www
  script:
  - ls
  only:
  - master
  dependencies:
  - build