stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .gradle

build:
  stage: build
  tags:
    - www
  artifacts:
    paths:
      - build/libs/*.jar
  script:
    - ./gradlew -Dorg.gradle.java.home=/opt/jdk-12 shadowJar --refresh-dependencies

test:
  stage: test
  tags:
    - www
  script:
  - ./gradlew -Dorg.gradle.java.home=/opt/jdk-12 check
  - ./gradlew detekt

deploy:
  stage: deploy
  tags:
    - www
  script:
    - sudo systemctl stop hm-animations-server.service
    - sudo cp -rf build/libs/animation-server.jar /opt/server.jar
    - sudo systemctl restart hm-animations-server.service
  only:
    - master
  dependencies:
    - build
